name: ncsw-data-env

channels:
  - conda-forge

dependencies:
  - pip
  - py7zr
  - rdkit
  - requests
  - tqdm
  - pip:
      - ord-schema
      - pqdm
      - pyarrow
      - sphinx
      - sphinx-autoapi
