name: ncsw-data-use-case-env

channels:
  - conda-forge

dependencies:
  - notebook
  - pip
  - py7zr
  - rdkit
  - requests
  - tqdm
  - pip:
      - ord-schema
      - pqdm
      - pyarrow
      - rdchiral
      - rxnmapper
